drop table if exists users, items, comments, bookings, items_request;

CREATE TABLE users (
user_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
name varchar(100) NOT NULL,
email varchar(100) UNIQUE NOT NULL
);

CREATE TABLE items_request (
request_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
description varchar(255) NOT NULL,
created TIMESTAMP WITH TIME ZONE NOT NULL,
owner_id  integer NOT NULL REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE items (
item_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
name varchar(255) NOT NULL,
description varchar(255) NOT NULL,
available boolean NOT NULL,
owner_id integer NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
request_id integer REFERENCES items_request(request_id) ON DELETE CASCADE
);

CREATE TABLE comments (
comment_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
text varchar(255) NOT NULL,
author_id integer NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
item_id integer NOT NULL REFERENCES items (item_id) ON DELETE CASCADE,
created TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE bookings (
booking_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
booker_id  integer NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
item_id    integer NOT NULL REFERENCES items (item_id) ON DELETE CASCADE,
status     integer NOT NULL,
start_date TIMESTAMP WITH TIME ZONE NOT NULL ,
end_date TIMESTAMP WITH TIME ZONE NOT NULL
);